### PR TITLE
bump patch version

### PR DESCRIPTION
**Pull request by simeonschaub**
cc @cstjean

### CODE REVIEW

**Comment by simeonschaub** [comment]
@cstjean Could you also tag this as a release?

**Comment by cstjean** [comment]
Sorry, I haven't done much OSS lately. 

https://github.com/FluxML/MacroTools.jl/commit/7723a86112fcd611c2776dc86bbc346de67602d5 😢 IIRC someone needs to make a manual PR to the registry.

**Comment by simeonschaub** [comment]
I am not sure whether JuliaRegistrator is set up here, but if it is, just commenting `@JuliaRegistrator register` on that commit should do the trick.

**Comment by simeonschaub** [comment]
(apparently it is)

**Comment by cstjean** [comment]
See https://github.com/FluxML/MacroTools.jl/commit/7723a86112fcd611c2776dc86bbc346de67602d5#commitcomment-43339341

**Comment by simeonschaub** [comment]
Ah, I see!

**Pull request merged**
