### PR TITLE
Ignore Manifest.toml

### PR DESCRIPTION
**Pull request by omus**

### CODE REVIEW

**Comment by omus** [comment]
Can we proceed with this?

**Comment by cstjean** [comment]
Why do you want it ignored? I thought keeping it was the official recommendation.

**Comment by tpapp** [comment]
AFAIK it constrains the resolver, so CI may run with some older versions of various packages.

**Comment by omus** [comment]
> AFAIK it constrains the resolver, so CI may run with some older versions of various packages.

In this case the package MacroTools is just using stdlibs so it's just using the versions Julia specifies. The motivation behind removing the Manifest.toml and ignoring it is that it's just not necessary in this case.

**Pull request merged**
