### PR TITLE
Fix CI by moving CI.yml to right place

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
See https://github.com/fingolfin/MacroTools.jl/actions/runs/1628491945 for a sample run

**Comment by fingolfin** [comment]
Also fixed the README.md to point to the new build status

**Comment by cstjean** [comment]
Also normal that CI did not run?

**Comment by fingolfin** [comment]
Whenever a 3rd party PR adds a new action, it is not run in the context of the target repository before the PR is merged, for security reasons: actions run in the context of the repository may have access to certain "secrets" (such as encryption keys) that not any arbitrary 3rd party should be able to view.

But now that you merged the PR, the actions *are* running here, as you can see at https://github.com/FluxML/MacroTools.jl/actions

**Pull request merged**
