### PR TITLE
Update pattern-matching.md

### PR DESCRIPTION
**Pull request by jkroso**
Explain why QuoteNode never matches

### CODE REVIEW

**Comment by jkroso** [comment]
```Julia
@match :(:a) begin
  s_QuoteNode => 1
  s_quote => 2
end
```

You might expect the first pattern to match but actually its the second one that does so the result of that expression is `2`.

**Comment by cstjean** [comment]
I see! Perhaps that example would be good to add to the PR.

Do you think it'd be reasonable to fix it? We can merge this PR in the meantime, but special-casing `QuoteNode` in the macro code doesn't sound that unreasonable.

**Comment by jkroso** [comment]
If the Julia parser only produces QuoteNodes for quoted symbols then it would make sense to change the way MacroTools handles QuoteNodes. And as far as I know that's the case but I’m not sure on that. In a sense then though MacroTools currently does special case QuoteNode so making it work the way I expected would mean removing that special case. Which is [just 1 line](https://github.com/FluxML/MacroTools.jl/blob/c9f9e98495d109cd354a6cc98e6c689c96fc3499/src/match/match.jl#L90)

**Comment by cstjean** [comment]
And that line comes from https://github.com/FluxML/MacroTools.jl/commit/1e01db99b35526d880846d351aff962367a378c3, 9 years ago, with not much to go on. 

The problem with MacroTools is that A) it is lacking test cases B) breaking it can break a good chunk of the Julia ecosystem...

Ah, I'd lean towards merging this PR at the moment unless we are really confident of the implications of removing that line. It's more or less a breaking change. Can you please add the example you posted above?

**Comment by jkroso** [comment]
Yeah I think the best we can do is document the odity for now. I reworded it to include the example. How does it read now?

**Comment by cstjean** [comment]
Perfect, thanks.

**Pull request merged**
