### PR TITLE
handle keyword defaults (i.e. Base.@kwdef)

### PR DESCRIPTION
**Pull request by colinxs**
Adds the ability to parse keyword default (i.e. Base.@kwdef) like:
```
Base.@kwdef struct Foo
x
y=5
end
```
I don't have the throughput right now to add any tests, but leaving this PR here for review (and in case anyone beats me to writing a test!). I'll circle back early July to add a test if it hasn't been done yet and you decide to merge this. I've been using this patch in my own codebase and haven't run into any issues (yet!).

-Colin

### CODE REVIEW

**Comment by MikeInnes** [comment]
I think I'm a bit unclear on the purpose of this. Is the idea that with this patch you could more easily implement the `@kwdef` macro? Are there other use cases for this? I'm a bit wary of adding support for non-standard syntax, especially if it's essentially useful to implement one particular macro.

**Comment by colinxs** [comment]
Hi Mike!

Sorry for the terse reply; I'm replying from my phone.

@kwdef is actually already in Base. I don't think it's in the documentation
yet, but you can find the docstring in the REPL. There's a GH issue
floating around that discusses it in more detail (and compares it to
Parameters.jl from which it was inspired).





Colin X Summers
University of Washington
Personal Robotics Lab
www.colinxsummers.com

**Comment by MikeInnes** [comment]
Right, so what benefit does this patch have, in that case?

**Comment by colinxs** [comment]
I misunderstood your question!

Without the patch, splitstructdef/combinestructdef don't really work. The
@kwdef syntax just gets classified as a constructor in splitstructdef
rather than as a field (with a default value).

Colin X Summers
University of Washington
Robotics and State Estimation Lab
Personal Robotics Lab
www.colinxsummers.com

**Comment by MikeInnes** [comment]
Sorry, I see that the patch adds support for that syntax, but I still don't see what the use case or benefit is for that change. Since it's syntax that's specific to one macro (`@kwdef`), rather than part of the base language, it seems like it's pretty limited; but I'd be interested to hear what you see this being used for.

**Comment by colinxs** [comment]
My specific use case, which prompted this patch, was [a discussion](https://discourse.julialang.org/t/autocomplete-for-contents-of-custom-type/8304/2) of a macro which adds type parameters where needed to yield a fully concrete struct definition i.e.
```
@autotype struct Foo
x
y::Integer
end
```
becomes
```
struct Foo{T1, T2 <: Integer}
x::T1
y::T2
end
```
I tried combining that with the `@kwdef` syntax but had to make this patch to handle the syntax. Since `@kwdef` is in Base, others may run into similar problems. 

- Colin

**Comment by MikeInnes** [comment]
The issue there is that it's still non-standard and specific to that one macro. If the syntax were actually added to the language that's a different issue of course. Maybe that's OK, as long as it doesn't affect the API in the more common case.

Would it work to instead call `macroexpand` inside your macro? That should, in principle, make it compatible with any other struct syntax modifier without needing the special case for `@kwdef`.

**Comment by colinxs** [comment]
Hi Mike,
Sorry for the extended delay; I was out of town.

I definitely see the reason to not special case this. I attempted versing the order of the macros (@autotype @kwdef instead of @kwdef @autotype) and using macroexpand, but it's a bit trick as @kwdef returns both the struct and a function with kwargs. As an example, for:
```julia
Base.@kwdef struct Foo                                  
    x = 10                                                            
end
```
is expanded into:
```julia
begin                                                            
    #= util.jl:749 =#                                                  
    begin                                                              
        $(Expr(:meta, :doc))                                           
        struct Foo                                                     
            #= REPL[2]:2 =#                                            
            x                                                          
        end                                                            
    end                                                                
    #= util.jl:750 =#                                                  
    Foo(; x=10) = begin                                                
        #= util.jl:728 =#                                          
        Foo(x)                                                     
    end                                                            
end
```
I attempted a combination of `@capture` and `postwalk`/`prewalk` to find the embedded struct definition but haven't had any luck. If you have any advice, I'd appreciate it, but I know you've got your hands full with Flux/Zygote, among other things.

-Colin

**Comment by MikeInnes** [comment]
The macrotools `flatten` function might be useful here. That'd remove all the redundant begin blocks, and then the struct def will just be the first thing in the block.

**Pull request closed without merging**
